version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - train-search
      - mailhog
    networks:
      - soa-network

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - soa-network

  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"   # Messaging port
      - "8161:8161"     # Web console
    networks:
      - soa-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"     # SMTP port
      - "8025:8025"     # Web UI port
    networks:
      - soa-network

  booking:
    build: ./booking
    ports:
      - "8070:8070"
    depends_on:
      - consul
    networks:
      - soa-network

  notification:
    build: ./notification
    ports:
      - "8095:8095"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_MAIL_HOST=mailhog
    depends_on:
      - consul
      - activemq
      - mailhog
    networks:
      - soa-network

  payment:
    build: ./payment
    ports:
      - "8072:8072"
    depends_on:
      - consul
    networks:
      - soa-network

  ticket:
    build: ./ticket
    ports:
      - "8071:8071"
    depends_on:
      - consul
      - activemq
    networks:
      - soa-network

  train-search:
    build: ./trainSearch
    ports:
      - "8089:8089"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      - consul
      - activemq
    networks:
      - soa-network

  user:
    build: ./user
    ports:
      - "8085:8085"
    depends_on:
      - consul
    networks:
      - soa-network

  train-operator1:
    build: ./trainOperator
    ports:
      - "8090:8090"
    volumes:
      - ./config/trainOperator1/application-instance.yml:/config/application-instance.yml:ro
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/config/application-instance.yml
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_APPLICATION_NAME=trainOperator1
    depends_on:
      - consul
    networks:
      - soa-network

  train-operator2:
    build: ./trainOperator
    ports:
      - "8091:8091"
    volumes:
      - ./config/trainOperator2/application-instance.yml:/config/application-instance.yml:ro
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/config/application-instance.yml
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_APPLICATION_NAME=trainOperator2
    depends_on:
      - consul
    networks:
      - soa-network

networks:
  soa-network:
    driver: bridge
