spring:
  application:
    name: booking
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        healthCheckInterval: 1s
        healthCheckPath: /actuator/health
        instance-id: ${spring.application.name}:${random.value}
        queryPassing: true
        preferIpAddress: true
        enabled: true
  datasource:
    url: jdbc:h2:mem:booking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8070
