apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: booking
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: booking
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: booking
    spec:
      containers:
        - env:
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul
            - name: SPRING_MAIL_HOST
              value: mailhog
          image: booking
          imagePullPolicy: Never
          name: booking
      restartPolicy: Always
