apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: consul
    spec:
      containers:
        - args:
            - agent
            - -dev
            - -client=0.0.0.0
          image: hashicorp/consul:1.20
          name: consul
          ports:
            - containerPort: 8500
              protocol: TCP
      restartPolicy: Always
