apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: consul
  name: consul
spec:
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
  selector:
    io.kompose.service: consul
