apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mailhog
  name: mailhog
spec:
  ports:
    - name: "1025"
      port: 1025
      targetPort: 1025
    - name: "8025"
      port: 8025
      targetPort: 8025
  selector:
    io.kompose.service: mailhog
