apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: train-operator2
  name: train-operator2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: train-operator2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: train-operator2
    spec:
      containers:
        - args:
            - java
            - -jar
            - /train-operator-service.jar
            - --server.port=8091
          env:
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_APPLICATION_NAME
              value: trainOperator2
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/config/application-instance.yml
            - name: SPRING_MAIL_HOST
              value: mailhog
            - name: TRAIN_OPERATOR_DATA
              value: data2.sql
          image: train-operator
          imagePullPolicy: Never
          name: train-operator2
          volumeMounts:
            - mountPath: /config/application-instance.yml
              name: config-volume
              subPath: application-instance.yml
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: trainoperator-instance2-config
