apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: train-search
  name: train-search
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: train-search
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose.yml -o ./k8s-manifests
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: train-search
    spec:
      containers:
        - env:
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul
            - name: SPRING_MAIL_HOST
              value: mailhog
          image: train-search
          imagePullPolicy: Never
          name: train-search
          ports:
            - containerPort: 8089
              protocol: TCP
      restartPolicy: Always
